### ISSUE TITLE
gerda inputs

### ISSUE THREAD

**Issue by sofia-calgaro** [sofia-calgaro/ZeroNuFit.jl#30]
check if we can get exactly the same limits (efficiencies? resolutions?) -- should be quick to check

**Comment by sofia-calgaro** [comment]
from gstr (one per partition):

![image](https://github.com/user-attachments/assets/26e195c5-af4e-413a-89a1-62b5711b1092)

**Comment by tdixon97** [comment]
I think we can probably close this now, since we did alot of tests..
