### ISSUE TITLE
1/sqrt(S) checks

### ISSUE THREAD

**Issue by sofia-calgaro** [sofia-calgaro/ZeroNuFit.jl#31]
implementation worked smoothly, but it was noticed the fit returns a worse limit when using a more informative prior of 1/sqrt(S) --> check what's going on 

![image](https://github.com/user-attachments/assets/1626d11e-5776-4c06-8518-31966d1a3400)

![image](https://github.com/user-attachments/assets/3efedd45-cf28-4907-a798-de612845a47a)

**Comment by tdixon97** [comment]
I get a posteror like that for L200 however for GERDA I get the expected shape:
![image](https://github.com/user-attachments/assets/a37594c4-4952-4483-a4d5-5f34bffc8f4d)
And I get a limit T12 > 1.98E26 yrs not so far from the expectation (plus made with low MCMC stat)
Perhaps the above was made accidentally using L200 not GERDA files.

**Comment by sofia-calgaro** [comment]
that was the case, my bad i was rushing - no need to check anymore
