### ISSUE TITLE
speed up fits with a large number of partitions 

### ISSUE THREAD

**Issue by sofia-calgaro** [sofia-calgaro/ZeroNuFit.jl#33]
Idea from GSTR-20-002:

![image](https://github.com/user-attachments/assets/ba43e5aa-004a-449d-92d2-4e63d06493b2)

**Comment by tdixon97** [comment]
We already do this :)

**Comment by sofia-calgaro** [comment]
it had to do more with the check of the accuracy but we can take it as granted to begin with, dik
