### ISSUE TITLE
Sampler (for sensitivity studies)

### ISSUE THREAD

**Issue by tdixon97** [sofia-calgaro/ZeroNuFit.jl#6]
We should write some code that generates fake data (events), as a function of the parameters. This allows to do 'posterior-predictive-checks' (i.e. goodness of fit), and extract sensitivity.
Should be fairly easy.
* loop over partitions
* compute the mu_k, and draw samples from it
* If N>0
* compute the PDF and sample from it to get an energy

**Comment by sofia-calgaro** [comment]
on NERSC can be automatized easily via SBATCH - example of a configuration for using legend containers while running the script.
Example at https://github.com/legend-exp/legend-analysis-toolkit/blob/main/scripts/nersc-job-submission/slurm_shared_legend_sw.sh

**Comment by sofia-calgaro** [comment]
Potential info needed for running sensitivity studies:
1. the path to the output folder of the fit we performed (there we already have the config saved, so no need to give a path in input, which is good so we avoid mismatches of configurations between the actual config we used and the potential one we could use when running the sensitivity study)
2. how many sampling do we want to perform (maybe an inline input?)
3. save fits in a reasonable way, i doubt we want to save ALL files for ALL fits (eg just data and some config info, maybe pdfs, BUT data are heavy to store)
4. save results under the same folder from where we got the previous results

**Comment by sofia-calgaro** [comment]
- h5/jld2 files weight ~ 300-400 MB per fit -> dont save them!
- save generated data as json (same format as events file used for real data)

**Comment by sofia-calgaro** [comment]
From call 10.9.2024: 
```
function sensitivity(idx, seed, same_config? (eg not to use the same statistics), output_path) 
    # generate with one config, fit with another config?
    
    # 0 : exclusion sensitivity -> sample from fit with S=0 (discovery -> fit with S!=0)
    
    # 1
    ZeroNuFit.get_data( ... generate data given an input [need also the output, different from the one of the real fit] ...)
    
    # 2
    # create the right 'config,output_path'
    # update: evt location, saving output location, (optional: change previous MCMC options)
    
    # (3)
    # ZeroNuFit.run_analysis( ... run the usual fit ... ) 
```

break it down like the following:
1. generate dataset - given an input config 
2. then fit over them - using the same config used for real data (+commands to overwrite some config entries, eg MCMC settings)

**Comment by tdixon97** [comment]
Can this be closed now?
